 version: 1.2
  workflows:
  name: hello_world
    subclass: WDL
    primaryDescriptorPath:/assoc-aggregate/assoc-aggregate.wdl
    testParameterFiles:
      - /assoc-aggregate/assoc-aggregate-terra-allele.json
